#!/bin/sh

set -e

PREREQ="overlayroot"

prereqs()
{
    echo "${PREREQ}"
}

case "${1}" in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/lib/initramfs-tools/bin/systemd-boot-mount-snapshot-modules /bin
copy_exec /usr/lib/initramfs-tools/bin/systemd-boot-snapshots-notify /bin
